language: python

python:
  - "2.7"
  - "3.4"

env:
    - DJANGO=1.8.1
    - DJANGO=1.7.8

install:
  - pip install -q django==$DJANGO --use-mirrors
  - python setup.py install

script:
  - python setup.py test

service:
  - redis-server
